one = input("what is your favorite animal? ")
two = input("what is your favorite thing about this animal? ")
three = input("what kind of climate do they live in? ")
four = input("Is your favorite animal a herbivore or carnivore? ")
five = input("what continet does your animal live on? ")
six = input("what is a fun fact about them? ")
seven = input("Is your animal aggresive to people? (is or isn't) ")
eight = input("Can you have it as a pet legally? (can or cannot)")
nine = input("How long does your animal live? ")
ten = input("have you seen your favorite animal in person? (have or have not")

print("Your favorite animal is " + one)
print("your favorite thing about this animal is " + two)
print("The " + one, "Lives in a " + three, "climate.")
print("The " + one, "is a " + four)
print("The " + one, "lives on " + five)
print("A fun fact about " + one, "is " + six)
print("The " + one, + seven, "agressive towards people. ")
print("You " + eight, "legally own " + one)
print("The " + one, "lives for " + nine, "years ")
print("You " + ten, "seen " + one, "in person")

