one = input("what is your favorite animal? ")
two = input("what is your favorite thing about this animal? ")
three = input("what kind of climate do they live in? ")
four = input("Is your favorite animal a herbivore or carnivore? ")
five = input("what continent does your animal live on? ")
six = input("what is a fun fact about them? ")
seven = input("Is your animal aggressive to people? (is or isn't) ")
eight = input("Can you have it as a pet legally? (can or cannot) ")
nine = input("How long does your animal live? ")
ten = input("have you seen your favorite animal in person? (have or have not) ")

def survey():
    print("Your favorite animal is " + one)
    print(f"Your favorite thing about this animal is {two}")
    print(f"The {one} lives in a {three} climate.")
    print(f"The {one} is a {four}")
    print(f"The {one} lives on {five}")
    print(f"A fun fact about the {one} is {six}")
    print(f"The {one} is {seven} aggressive towards people.")
    print(f"You {eight} legally own a {one}")
    print(f"The {one} lives for {nine}")
    print(f"You {ten} seen the {one} in person")

survey()
